sonar.projectKey=xavier-ropero_ci-back
sonar.organization=xavier-ropero
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
