name: Back Spring Boot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Build and test
        working-directory: back
        run: mvn -B verify

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco

      - name: 🔎 Analyse SonarCloud via Maven
        working-directory: back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=xavier-ropero:bobapp-backend \
            -Dsonar.organization=xavier-ropero \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ env.SONAR_TOKEN }} \
            -Dsonar.sources=src/main/java \
            -Dsonar.tests=src/test/java \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.junit.reportPaths=target/surefire-reports \
            -Dsonar.jacoco.reportPaths=target/jacoco.exec \
            -Dsonar.javascript.lcov.reportPaths=../front/coverage/bobapp/lcov.info \
            -Dsonar.test.inclusions=**/*.spec.ts \
            -Dsonar.exclusions=**/*.spec.ts
