name: Back Spring Boot CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout du code
        uses: actions/checkout@v4

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 📦 Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: 🔨 Compile
        run: mvn compile
        working-directory: back

      - name: 🧪 Test
        run: mvn test
        working-directory: back

      - name: 🧪 JaCoCo Report
        run: mvn jacoco:report
        working-directory: back

      - name: 📂 Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/index.html

      - name: 📦 Package (skip tests)
        run: mvn verify -DskipTests=true
        working-directory: back

      - name: 📂 Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: back/target/*.jar
      #
      # � apr�s �?? Upload JaCoCo Report� ou juste avant la fin du job �
      #
      - name: ?? Analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        with:
          projectBaseDir: back
          args: |
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.organization=xavier-ropero
            -Dsonar.projectKey=xavier-ropero:bobapp-backend
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=src
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes
